# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project
        run: |
          mvn --batch-mode clean package -DskipTests=true
          mv target/expander-*-jar-with-dependencies.jar target/midpoint-expander.jar

      - name: Upload Expander
        uses: actions/upload-artifact@v4
        with:
          name: Midpoint Expander
          path: target/midpoint-expander.jar
          if-no-files-found: error

      - name: Extract Latest Changelog Entry
        run: awk '/^## \[/{if (p) exit; p=1} p' CHANGELOG.md > latest_changelog.md

      - name: Create Release
        run: |-
          gh release create ${GIT_TAG} \
            --title "Release ${GIT_TAG}" \
            --notes-file latest_changelog.md \
            target/midpoint-expander.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_TAG: ${{ github.ref_name }} # https://docs.github.com/en/actions/reference/workflows-and-actions/variables
